services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: producao-dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: producao-app
    ports:
      - "8082:8082"
    depends_on:
      - dynamodb-local
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://dynamodb-local:8000
      - SERVER_PORT=8082
      - SQS_ENABLED=false