services:
  mongodb:
    image: mongo:latest
    container_name: producao-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
    container_name: producao-app
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/fiap-producao-db
      - SERVER_PORT=8082

volumes:
  mongo_data:
