apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DATABASE_HOST: mysql
  DATABASE_PORT: "3306"
  DATABASE_NAME: lanchonete
  MP_URL: "https://api.mercadopago.com/"
  MP_USER_ID: "2461182756"
  MP_EXTERNAL_POS_ID: "113730756"
  MP_WEBHOOK: "http://54.165.29.101:30080/api/webhook/payment"
