apiVersion: v1
kind: Service
metadata:
  name: lanchonete-api-service
spec:
  type: NodePort
  selector:
    app: challenge-fiap-api
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080