name: CI/CD - Build, Push Docker Image to ECR, and Deploy to EKS

on:
  workflow_run:
    workflows: ["Quality Analysis"]
    types:
      - completed

  workflow_dispatch:

jobs:
  build-push-deploy:
    uses: fiap-challenge-group-52/challenge-fiap-workflows/.github/workflows/build-push-ecr.yaml@feature/reusable-workflows
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
